### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Kenny-Haworth/Harvest-Moon-2.0#29]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPLv3 or AGPLv3 license so that others are encouraged to contribute changes back to your project.

**Comment by bunnitech** [comment]
Hmm without a license it'll be impossible to build on this. GPL has some inheritance problems big enough that many companies and government agencies now prohibit adopting GPL licensed work, and doesn't cover artwork well. There is a discussion, one of many, here: https://opensource.stackexchange.com/questions/2860/how-do-you-use-gplv3-icons-in-non-software-artwork

I would use CC-BY-4.0 to make future contributors' lives easier. I'm working on a project right now which has GPL headaches, the FSF itself doesn't recommend GPL/AGPL for non-software assets. That, or the eff-it license, a.k.a. MIT license seems to hold its weight for most use cases.

**Comment by TechnologyClassroom** [comment]
The reasons some companies do not want to use the GPL is because those companies only want to make proprietary software.

It is common to license artwork under CC BY-SA and code under a GPL license.

**Comment by protonesso** [comment]
use isc

**Comment by Kenny-Haworth** [comment]
Thank you for bringing this to my attention. I have added an appropriate MIT license which allows anyone to modify and contribute to the project as they see fit. Please link back to the source if you choose to continue development on my project - I would love to see what others do with it.
